### ISSUE TITLE
Error Stack Traces are Broken

### ISSUE THREAD

**Issue by thesunny** [thereactivestack/kickstart#1]
First of all, I absolutely love this project.

I tried to use the other meteor-webpack-react project but had so much trouble figuring out what was going on that I abandoned it. I've been trying to figure out a manageable way to get hot reloading working with React. After I saw your project, I converted my project to use it within a day. Fantastic work.

The major issue for me, however, is that the error stack traces are broken to the point that it could seriously impede development. It often throws error that don't show any lines from my source code. I didn't have this problem when I wasn't using Webpack.

With so many files, it could be almost impossible to track down where an error was.

Would be great to fix this bug. If I have time, I'll try and work on this some more (I took a small stab at it) but I have a feeling your experience is better than mine in this field.

**Comment by thesunny** [comment]
It seems to be related to this problem on the other meteor-webpack-react:

https://github.com/jedwards1211/meteor-webpack-react/issues/40

I was using devtool: eval-source-map (or something like that) so the stack was completely broken.

Apparently removing redbox and adding the source maps in devtool: will give you accurate line numbers.

This might be preferable for this default project as well because with redbox, the error messages are actually obscured in my app because of some dom elements that happen to cover them. Since we can't know which projects will use this boilerplate, the default handling of error messages might be preferable than using Redbox, especially in light of the inaccurate error stack trace.

**Comment by eXon** [comment]
The redbox will not be removed from this project. I'll try to find a way to fix the line. The stack trace shouldn't be broken outside the file line however. I'll try with the new version and look what I can do.

**Comment by thesunny** [comment]
Hi exon, thanks for the response. I found out why the file was wrong. I tried fixing it myself and used devtool: "cheap-module-eval-source-map" and though that was (theoretically) supposed to put in the source maps, it actually wrecked the file mapping and only sometimes fixed the line numbers.

**Comment by skosch** [comment]
@eXon, @thesunny, have you found a configuration that works? I love, love, love this project, but frankly the benefit of the hot-reload is completely negated right by the extra time I now spend blindly hunting for typos in my code because the line numbers are useless :(

**Comment by eXon** [comment]
@skosch I agree line numbers are important.

I've changed the devtool to inline-source-map and removed react-redbox. It seems to be the only way to have the correct line numbers. Let me know if it works for you too!

**Comment by skosch** [comment]
That does work, thank you! Sucks that redbox isn't working though, it was a neat gimmick

**Comment by thesunny** [comment]
@eXon, I'm glad you changed your mind with respect to removing Redbox. It would have been great to have it work with Redbox but barring that, having the right line numbers seems to be the better tradeoff.

FYI, I've been using "cheap-module-eval-source-map" which will be the new default for WebPack and it works as well. There may be some performance advantages with respect to rebuild speed in this mode (though unfortunately the chart doesn't show "inline-source-map" in its performance comparison).

https://webpack.github.io/docs/configuration.html#devtool

**Comment by eXon** [comment]
@thesunny awesome, I though it was only working with source-map and I was angry at how slow it became. I'll fix this right now in dev.
