### ISSUE TITLE
How to use semantic ui

### ISSUE THREAD

**Issue by etamity** [thereactivestack/kickstart#15]
Hi,
I am trying to use semantic ui in this kickstart, but after I installed semantic ui package in Meteor folder,
the style didn't show correctly.

here is my code:
```
import { Component } from 'react';
import ReactMixin from 'react-mixin';
export default class TodoApp extends Component {
  componentWillMount() {
  }
  render (){
		return (
		<div>
			<div className="ui large top fixed hidden menu">
			  <div className="ui container">
			    <a className="active item">Home</a>
			    <a className="item">Work</a>
			    <a className="item">Company</a>
			    <a className="item">Careers</a>
			    <div className="right menu">
			      <div className="item">
			        <a className="ui button">Log in</a>
			      </div>
			      <div className="item">
			        <a className="ui primary button">Sign Up</a>
			      </div>
			    </div>
			  </div>
			</div>

			<div className="ui vertical inverted sidebar menu">
			  <a className="active item">Home</a>
			  <a className="item">Work</a>
			  <a className="item">Company</a>
			  <a className="item">Careers</a>
			  <a className="item">Login</a>
			  <a className="item">Signup</a>
			</div>

		</div>

		  )
	 }

```

**Comment by etamity** [comment]
Sorry, my mistake,  should install package with less-autoprefixer
meteor add semantic:ui flemay:less-autoprefixer

**Comment by khrykin** [comment]
Have another issue with semantic UI, any help please...
Followed installation instructions on Atmosphere, styles works great, but no semantic-ui specific js seem to be available (checked in browser console —  `$('.ui.dropdown').dropdown();` is `undefined` as well as in `componentDidMount`), jQuery works well though

**Comment by eXon** [comment]
Which atmosphere package have you used?

**Comment by khrykin** [comment]
Super-official `semantic:ui`

**Comment by eXon** [comment]
You should have a `definitions/` folder with javascript files. You need to import dropdown if you want it to work. JS files are not automatically loaded.

**Comment by khrykin** [comment]
Hmm... but all my definitions aren't wrapped in `export` object and generated automatically when i change `custom.semantic.json`, so how do I import them?  Is there any solution to import them automatically and control their presence from `custom.semantic.json` file? Sorry for dumb questions
