### ISSUE TITLE
Hot-reload not auto-updating?

### ISSUE THREAD

**Issue by andreasbhansen** [thereactivestack/kickstart#16]
Hi,

I cloned your repo and ran ```npm install```, then ```./scripts/run-dev.sh```. It seems as if everything works fine. On ```:3000``` the Todo app is running, and I'm able to register, log in, post todos, etc..

However, I'm not able to hot-reload the view. I tried changing the ```<h1>Todo List</h1>``` in the ```TodoHeader.jsx``` file to ```<h1>Todo List2</h1>```, but the change was not displayed in the browser (Chrome/Firefox, tried both), unless I manually refresh the page. The terminal outputs ```webpack building... webpack built [...] in 274ms```.

However, in the Chrome console, I get an error message: 
```EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.````

Is this related to hot-reload not working properly?

**Comment by eXon** [comment]
You should have the webpack dev server running on port 3500. If you got the message `webpack building...` it means it was running. 

Did you started with a fresh clone or was it a migration? Make sure your webpack/development.config.js is having this:

```javascript
entry: [
  'webpack-hot-middleware/client?path=http://localhost:3500/__webpack_hmr',
  './react'
]
```

If you look at the request to `__webpack_hmr`, was it using localhost:3500? If it use localhost:3000, there is something wrong.

Let me know if it helps

**Comment by andreasbhansen** [comment]
Ok, so I checked the ```webpack/development.config.js``` and it does contain the snippet you posted.

However, looking at the request, it does indeed go to ```http://localhost:3000/__webpack_hmr```, instead of ```:3500```. Any idea why?

**Comment by eXon** [comment]
On what OS are you? I tried with Linux and Windows and it works fine.

**Comment by andreasbhansen** [comment]
I'm on OS X Yosemite (10.10). I can try on my Windows machine later today. Still, weird that it sends requests to ```:3000```.

**Comment by kimsk** [comment]
@andreasbhansen I am also on Yosemite (10.10.5), but I don't experience the issue with the fresh clone. Hot-reload seems to work fine without refreshing the page.

```
webpack building...
webpack built dfde3114dd71e384b030 in 256ms
webpack building...
webpack built 5521fca62d8a7d4b59d7 in 149ms
```

The changes are super fast. Thanks @eXon

**Comment by andreasbhansen** [comment]
Thanks for checking, @kimsk. I tried cloning again, and indeed it works as expected. No idea what went wrong the first time I cloned. I assume this can be closed, @eXon.
