### ISSUE TITLE
run-dev.bat not detecting changes on Windows 10

### ISSUE THREAD

**Issue by john-osullivan** [thereactivestack/kickstart#18]
I'm working from a cloned and unchanged version of this repository and the `run-dev.bat` script doesn't seem to be working as intended.  Once the script has finished its first run of webpack, it never responds to any changes in the source files and never rebuilds.  In order to successfully view changes, I need to end the process, close the node terminal which ran webpack, and re-run the script.  This is a far cry from the workflow I was imagining, any tips on how to fix this?

**Comment by eXon** [comment]
Have you try to set this to your `webpack/development.conf.js`:

```javascript
watchOptions: { poll: true }
```

Windows has no native watch file and it might not detect it is Windows 10.

Let me know if it works!

**Comment by john-osullivan** [comment]
I added that into module.exports, tried changing the AdminApp, and unfortunately, it didn't work.

**Comment by eXon** [comment]
Thank you, happy Thanksgiving too. This project has been deprecated in favor of `kickstart-simple` and `kickstart-hugeapp`. Let me know if you're having problem with them.
