### ISSUE TITLE
SSR error on server

### ISSUE THREAD

**Issue by rclai** [thereactivestack/kickstart#2]
I ran your kickstarter project as is in production mode, and I see this on my server log (in addition with your S1, S2, S3 logs lol):

```
Warning: Location "/packages/reactrouter:react-router/react-router.browserify.js" did not match any routes
```

However, the app still works though.

**Comment by eXon** [comment]
The console.log should be released in the next version, sorry about that xD

For the warning I'll take a look.

**Comment by eXon** [comment]
I updated the project. Do you still have this error?

**Comment by rclai** [comment]
Let me check.

**Comment by rclai** [comment]
The error is gone.
