### ISSUE TITLE
Please one more project without router?

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart#20]

**Comment by eXon** [comment]
Why would you want a project without any router? It seems pretty basic to me. The kickstart-simple has only one route but your project will certainly need more.

**Comment by SenerDemiral** [comment]
Because, I want to convert React-Redux experemantal project. But I couldn't with router and going down.

**Comment by SenerDemiral** [comment]
Maybe, flowrouter project helps me more.

**Comment by eXon** [comment]
I'm not planning on doing another project that I will need to maintain. I'm sure you can easily figure it out with kickstart-simple or kickstart-flowrouter like you said.
