### ISSUE TITLE
Reloading server files

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart#21]
Hi, thanks for the great work here!

I have an issue with server imports which do not get reloaded when modified.
For example i import a publication file in `/server/entry.js` such as `import "MyApp/modules/notifications/notifications_publications";`

But, whn I modify this imported file the server does not reload and I have to manually stop and start the server to reload changes. This is quite lengthy. Do you have any advice on how can I make this work? I tried to modify aleo entry.js which triggers the server rebuild, but it still does not consider my changes and full restart is required. Thanks.

**Comment by tomitrescak** [comment]
I've found the culprit. It is the awesome-typescript-loader. Any idea how can this be dealt with?

**Comment by eXon** [comment]
Oh I get your problem. It is because the WebpackCompiler is not watching for .ts or .tsx files. I don't know if I can add it safetly to the watched files, I'll have to investigate a little bit. I guess it doesn't make sense to use Webpack and a TypeScript package.

**Comment by tomitrescak** [comment]
Hi, I have a quite large typescript project working with your webpack solution.
This is one of the last glitches.

How about enabling WebpackCompiler watch over extensions defined in the webpack config?

```
resolve: {
    root: path.join(__dirname, '..', 'modules'),
    extensions: ['', '.js', '.jsx', '.ts', '.tsx', '.json', '.css', '.scss']
  }
```

**Comment by tomitrescak** [comment]
Also, one off-topic. After every client file (compoennt) modification the webpack is rebuilding. I get the immediate change with hot code reload, but it is then waiting for data until server restarts, Any idea why is this happening?

**Comment by eXon** [comment]
I can't really tell unless I see your code inside `getMeteorData()`

**Comment by eXon** [comment]
TypeScript extensions are now being watched by Webpack :)

**Comment by tomitrescak** [comment]
Hi @eXon has anything changed recently? Server files are ignored again. Thanks

**Comment by eXon** [comment]
No. Can you be more specific with your problem?

**Comment by tomitrescak** [comment]
Hi I reported it in the kickstart main issues page. After modifying ts files belonging to server, the server is correctly restarted but webpack does not produce a build. Therefore the only way to get webpack to rebuild server files is to restart the whole server or modify webpack.conf.js file or any other server js file.

**Comment by tomitrescak** [comment]
I could reproduce with any setup.

**Comment by tomitrescak** [comment]
Hi, I have added the description at thereactivestack/kickstart-simple#31

**Comment by eXon** [comment]
I'll close this one because this repo isn't really relevant to the bug. I'll follow up on your kickstart-simple issue.
