### ISSUE TITLE
Control statements

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart#22]
Just a small suggestion ;) Coming from the Blaze meteor development environment I would love to have known that there is this NPM package that integrates so well with your webpack package:

https://www.npmjs.com/package/jsx-control-statements

All that was needed to do was to add it to NPM and a list of plugins 

```
babelSettings.plugins = ['react-transform', 'jsx-control-statements/babel'];
```

And now I can write my `<If>` and `<For>` loops more clearly.

Just writing if you would consider it in the base of your pack, helped me a lot.

**Comment by eXon** [comment]
I don't plan on building an example with this. I don't want to go this far but it's great to know it serve you well!
