### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart#23]
Hi, just wondering why is the kickstart App constantly using 20-40% of CPU? This only happend in the dev mode. Production is ok, Thanks.

**Comment by eXon** [comment]
I bet if you remove the tests folder it would not. It is because velocity is starting mirrors for integration tests :)

**Comment by tomitrescak** [comment]
Hi, I do not have test folder in my project ;( Could it be something else?

**Comment by tomitrescak** [comment]
Here is a gif of devel version:

![webpack](https://cloud.githubusercontent.com/assets/2682705/11392284/c31e7694-93ac-11e5-9b50-4199dd00a8d2.gif)

Here is gif for production version:

![webpack2](https://cloud.githubusercontent.com/assets/2682705/11392330/15bf29c0-93ad-11e5-9e62-51b643a14c1b.gif)

**Comment by tomitrescak** [comment]
One more detail, I do not have velocity package installed in the project.

**Comment by eXon** [comment]
I'll investigate more on this when I have time. Is it still an issue?

**Comment by tomitrescak** [comment]
Yes it is. I compared this to @jedwards approach and his solution was also running at 30% CPU. Must be the mirror or file watch .. not sure.

**Comment by jedwards** [comment]
Hey guys,

Can I just say, I keep getting these emails. Definitely nothing to do with
me, so you might need to check the email address to get these to the right
person :)

Regards,

On 15 December 2015 at 16:39, Tomas Trescak <notifications@github.com>
wrote:

> Yes it is. I compared this to @jedwards <https://github.com/jedwards>
> approach and his solution was also running at 30% CPU. Must be the mirror
> or file watch .. not sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/kickstart/issues/23#issuecomment-164821219>
> .
>



-- 
Jack Edwards
07898109853
Dover Franchisee
www.facebook.com/CeXdover
A CeX franchise owned & operated
under licence by: EEX Limited

**Comment by eXon** [comment]
I'm not sure an action is needed here. Thanks for reporting your issue :)
