### ISSUE TITLE
Tests with Wallaby.js

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart#24]
@eXon please would you mind sharing information on where the webpack files are built? I'm trying to figure out if I can make your solution work with the awesome TDD and BDD tool wallaby.js.

The unit tests work quite well but no luck with integration yet.
Wallaby integrates very well with React and webpack so am wondering if it would be possible.

Thanks!

**Comment by eXon** [comment]
I've never used Wallaby before. Do you have an example of it working with Meteor?

Is it still relevant?

**Comment by tomitrescak** [comment]
Yes it is .. unfortunatelly there is no example for meteor, but there are examples for webpack:

http://wallabyjs.com/docs/integration/webpack.html

I was thinking of watching the client and server build files for testing.

**Comment by eXon** [comment]
I'm not sure this will be easy to integrate with Webpack. I'll close this one because it doesn't belong on this repo but feel free to open one in the [meteor-webpack](https://github.com/thereactivestack/meteor-webpack) repo.
