### ISSUE TITLE
Mantra

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart#25]
Hi, with the release of Meteor 1.3, would you consider also to create a kickstart for [Mantra (https://github.com/kadirahq/mantra)](https://github.com/kadirahq/mantra) projects? If so, would be great! ;) Keep up the great work!

**Comment by eXon** [comment]
I think webpack would be a great tool to include within Mantra for everyone so I am currently looking into working with them. :)

**Comment by tomitrescak** [comment]
@exon I have [created a boilerplate](https://github.com/tomitrescak/Meteor-Boilerplate-Webpack-Mantra-Typescript) that ported Mantra into your solution and some people are already using it. But it is working with Meteor 1.2. Havin yours officially supported one would be much better.

**Comment by eXon** [comment]
Thank you @tomitrescak I'll take a look, I'm sure it will be helpful.

**Comment by eXon** [comment]
Added your kickstart to the list :+1:
