### ISSUE TITLE
Adding webpack sass-loader issues

### ISSUE THREAD

**Issue by epitaphmike** [thereactivestack/kickstart#6]
Has anyone been able to successfully add webpack [sass-loader](https://github.com/jtangelder/sass-loader) to this? 

I am getting this error when using sass-loader. Current installed version of node is v4.0.0

> Error: The libsass binding was not found in ../node_modules/node-sass/vendor/darwin-x64-11/binding.node
> (STDERR) This usually happens because your node version has changed.
> (STDERR) Run npm rebuild node-sass to build the binding for your current node version.
> (STDERR) at Object.sass.getBinaryPath (../node_modules/node-sass/lib/extensions.js:150:11)

Output after running `npm rebuild node-sass`

> node-sass@3.3.3 install ../node_modules/node-sass
> node scripts/install.js

> node-sass@3.3.3 postinstall ../node_modules/node-sass
> node scripts/build.js

> ../node_modules/node-sass/vendor/darwin-x64-46/binding.node exists. testing binary.
> Binary is fine; exiting.
> node-sass@3.3.3 ../node_modules/node-sass

Wiping the `node_modules` folder and running `npm install` yields the same results unfortunately.

The libsass binding is looking for vendor/darwin-x64-11/binding.node, while the one installed is vendor/darwin-x64-46/binding.node.

There is nothing explicit pointing to /vendor/darwin-x64-11/binding.node, but when I manually added /vendor/darwin-x64-11/binding.node I would start getting different build errors related to LazyResult.async.

> ERROR in /meteor-webpack-react-kickstart/~/css-loader!/meteor-webpack-react-kickstart/~/sass-loader!/meteor-webpack-react-kickstart/react/todo/sass/Main.scss
> ? Module build failed: ReferenceError: Promise is not defined
> ? at LazyResult.async (/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)

Any assistance or additional testing would be appreciated.

**Comment by eXon** [comment]
I'm getting the same error. The project should be updated soon with css and sass loader.

**Comment by eXon** [comment]
I made a pretty big update to the project. Now you can require CSS / SCSS files.

If you want this error fixed, you need to make sure your global Node.js has the same version than Meteor Node.js. Mine was on 0.10.40. I added a note on the readme.

Let me know if it works for you!

**Comment by epitaphmike** [comment]
Your update allows me to load a css file via the new componentWillMount, but as soon as I replace it for a sass file, I get the same error. I am able to see that I am running node v 4.0.0 globally, but I cannot see what version I am running in meteor. I tried using mnode, but keep getting an error about not running the meteor app. Do you have this working with node 4.0.0? Node is currently at version 4.1.1. Thank you for the time you have spent in this repo.

**Comment by eXon** [comment]
I found a way, let me fix my script :)

**Comment by eXon** [comment]
Add this to `scripts/run-dev.sh` just before the ROOT_FOLDER:

```bash
# Run this script in Meteor to find your own value:
# console.log(process.platform + '-' + process.arch + '-' + process.versions.modules);
# Then, remove node_modules/node-sass and run this script again
export SASS_BINARY_NAME=linux-x64-11
```

If it's not the correct value, fix it, remove the node_modules/node-sass and run the script again.

Does it work for you with 4.1.1? It worked for me with 0.12.

**Comment by eXon** [comment]
This tell node-sass to compile for the Node version you are running with Meteor. It's a real pain in the ass to find this value unless you just run this simple line with Meteor. Hopefully it will be simple enough.

**Comment by yasinuslu** [comment]
I thought that the problem is with node-sass and wrote a post [here](https://github.com/sass/node-sass/issues/753#issuecomment-143421812)

**Comment by eXon** [comment]
I updated the project with a better fix. If you have this error, open scripts/fix-ssh.sh, change the SASS_BINARY_NAME value by what you have between vendor and binding.node and run the script.

In the original error:
```
Error: The libsass binding was not found in ../node_modules/node-sass/vendor/darwin-x64-11/binding.node
(STDERR) This usually happens because your node version has changed.
(STDERR) Run npm rebuild node-sass to build the binding for your current node version.
(STDERR) at Object.sass.getBinaryPath (../node_modules/node-sass/lib/extensions.js:150:11)
```

You can see the freaking value is there: ../node_modules/node-sass/vendor/**darwin-x64-11**/binding.node

Can't be easier than that :)

Let me know if you're still having troubles.

**Comment by epitaphmike** [comment]
So it seems this issue persists.... I am not sure what I am doing incorrectly, but I have tried a lot.

I am still getting the following error.

>Error: The `libsass` binding was not found in ../kickstart/node_modules/node-sass/vendor/**darwin-x64-11**/binding.node

At this point, I have cloned the new repo, edited the `fix-sass.sh`, in that file I have set the 

>SASS_BINARY_NAME=**darwin-x64-11**
>NODE_VERSION=v0.10.40

I have tried setting the **`SASS_BINARY_NAME`** to the version I have in node_sass, 
which is **`vendor/darwin-x64-46`** as well as setting the **`NODE_VERSION`** to what I am currently running locally **`v4.1.1`** all without any luck.

in App.jsx I have the following

>componentWillMount() {
    require('./sass/styles.scss');
  }

I really don't know what I am missing here. I appreciate the help you are providing. 

Also, I did notice there are **a lot** more dependencies (in the hundreds) in node_modules than there was before.

**Comment by eXon** [comment]
It seems to be a problem only on Mac. I'll try to get one and figure out why this isn't working.

**Comment by xor125** [comment]
I can confirm this happens on a PC with win 8.1. I'll try it on a win 10 and drop a comment here

**Comment by eXon** [comment]
I've fixed the script. Let me know if it works for you.
