### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by tvararu** [thereactivestack/kickstart#8]
Firstly, good job on building this!

It's just what I was looking for, save for a few (what I consider to be) improvements I've done on my fork. If there's anything you'd like me to merge back through a pull request, I'd be more than happy to submit one. You can also just cherry-pick the commits yourself or re-implement them, as you see fit. :)

You can check the commit log at https://github.com/tvararu/meteor-webpack-react-kickstart/commits/master. Here's a summary of what I've added:

- Allow users to use ES6 classes exclusively by adding [react-mixin](https://github.com/brigand/react-mixin) to solve the `ReactMeteorData` issue. Also, refactor `propTypes` to `static propTypes` and `.bind(this)` functions to class property initializer ones.
- Add path resolvers to the Webpack configuration so you can require components from the root of the `./react` folder as opposed to relative from the file location. For example, `require('components/Button')` instead of stuff like `require('../../Button')`. This makes moving components around without having to refactor tons of `require` calls trivial.
- Lint the project using [standard](https://github.com/feross/standard) and add a pre-push hook to automatically lint before pushing.

One thing I also tried doing which was unsuccessful was leveraging the `scripts` section of `package.json` to run the various shell scripts in `./scripts`. However, this caused my node process to hover at around 160% usage and make my laptop catch on fire. I don't know why this is the case.

If you don't need anything from here, feel free to close the issue.

**Comment by eXon** [comment]
Hey @tvararu 

Thank you for the feedback, I think you have a lot of great ideas.

- I agree the static propTypes syntax is much better
- I would rather stick to the official mixin, I don't want to introduce new concepts like react-mixins (I don't think they will with it for very long anyway)
- Great idea for the linter! I added eslint because I feel like it has a stronger JSX support and integration with Atom/Sublime (disclaimer: I don't know very much about standard)

I've merged manually because it was simplier for me.

Next step: adding some unit tests :) This project is getting better and better thank you! Let me know if you have other ideas to improve the project.

**Comment by tvararu** [comment]
Glad to see I could help!

> I would rather stick to the official mixin

Fair dos. This is reasonable given that you want the boilerplate to be used by people of varying skill levels. It may be worth adding a small note in the readme about the `react-mixin` alternative for people like me that like having all their components consistent. Up to you!

> I added eslint because I feel like it has a stronger JSX support and integration with Atom/Sublime

`standard` uses `eslint` underneath! In fact, `standard` is just an opinionated set of options for `eslint` and `jscs`. As such, there should be no difference in the way they perform. The reason I use `standard` is because after spending a lot of time in the past moving around `.rc` files and fiddling with linters I've become tired myself of the linting game, so I just want a batteries included solution with sensible defaults.

Many other projects agree, such as [npm/npm](https://github.com/npm/npm/commit/b50be6aff34a739ca43de65f546e743d1a9975b9), but in the end it's your decision as package maintainer. :)

I'll close this issue, glad to have been of help.
